config/routes.rb
Rails.application.routes.draw do
  resource :tasks, :only => [:index, :create, :update]
  put "tasks/:id", to: "tasks#update", as: :update_tasks
  root to: 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :description, presence:true
  scope :completed, -> { where(completed: true) }
  scope :incomplete, -> { where(completed: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to root_path
  end

  def update
    @task = Task.find(params[:id])
    @task.update(completed: true) ? flash[:notice] = "Completed" : flash[:notice] = "Error"
    redirect_to root_path
  end

private

  def task_params
    params.require(:task).permit(:description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p id="notice"><%= flash[:notice] %></p>

  <%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<div class="wrapper">
  <h1> To-do list </h1>
  <div class="container with-border">
    <h2> To be done </h2>
    <% @tasks.incomplete.each do |task| %>
      <div class="col">
        <ul>
          <li class="with-border push-top"><%= task.description %></li>
          <li>
            <%= form_tag update_tasks_path(task), method: "put" do |f| %>
              <%= submit_tag "Complete", class: "btn btn-large btn-primary push-top" %>
            <% end %>
          </li>
        </ul>
      </div>
    <%end%>

    <%= form_for :task, url: tasks_path do |f| %>
      <%= f.text_field :description, class: "text_field" %>
      <%= f.submit "Add new task", class: "btn btn-large btn-secondary" %>
    <%end%>
  </div>

  <div class="container with-border crossed-out">
    <h2>Completed tasks</h2>
    <% @tasks.completed.each do |task| %>
      <div class="col">
        <ul>
          <li class="with-border"><%= task.description %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>